### ISSUE TITLE
[BUG] Server Display Bug

### ISSUE THREAD

**Issue by JanTuck** [BestOfAllCoding/SUPLauncher-Reborn#16]
**Describe the bug**
I am currently on CWRP, not danktown, but the launcher says I am on danktown.

**To Reproduce**
1. Use the launcher, but do not launch using it. (Or simply join CWRP?)

**Expected behavior**
It should say "Current playing CWRP" or anything similar

**Screenshots**
![Issue](https://puu.sh/JezhL/55ea1a2cd0.png)

**Comment by aidanH39** [comment]
This will be fixed soon. Going to include this patch with the new update coming soon.

**Comment by aidanH39** [comment]
https://github.com/BestOfAllCoding/SUPLauncher-Reborn/commit/9b5cfdc14560d4eb8215bac2a3ae5c0b42ba5d78

Think this was just a visual bug. As when the text is not updated the default would have been "playing danktown"

If your text was not updating this could be due to your profile being offline / private as then it cannot read your current server.

I have change the default text to "Not Currently Playing SUP"
